#!/usr/bin/php
<?php
use Doctrine\DBAL\Tools\Console\Helper\ConnectionHelper;
use Doctrine\ORM\Tools\Console\Helper\EntityManagerHelper;
use Doctrine\ORM\Tools\Console\ConsoleRunner;
use Symfony\Component\Console\Helper\HelperSet;
use {namespace}\Infrastructure\Persistence\Doctrine\EntityManagerFactory;

if(!defined('DS'))
    define('DS', DIRECTORY_SEPARATOR);

$autoload = dirname(__DIR__) . DS . 'vendor' . DS . 'autoload.php';
require_once $autoload;

// Any way to access the EntityManager from  your application
$em = EntityManagerFactory::getNewManager();

$helperSet = new HelperSet(array(
    'db' => new ConnectionHelper($em->getConnection()),
    'em' => new EntityManagerHelper($em)
));

ConsoleRunner::run($helperSet);